import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';

double kSizedBoxSpace = 30;

InputDecoration customInputDecoration({
  // IconData? suffixIcon,
  String? labelText,
  String? errorText,
  // Function()? func,
  Widget? iconBtn,
}) {
  return InputDecoration(
    errorStyle: GoogleFonts.pressStart2p(fontSize: 8),
    errorText: errorText,
    suffixIcon: iconBtn,
    hintText: labelText,
    hintStyle: GoogleFonts.pressStart2p(
      fontWeight: FontWeight.bold,
      color: Colors.black,
    ),
    fillColor: Colors.white,
    filled: true,
    labelStyle: GoogleFonts.pressStart2p(color: Colors.blue[900]),
    floatingLabelStyle: GoogleFonts.pressStart2p(color: Colors.black),
    border: OutlineInputBorder(
      borderSide: BorderSide(color: Colors.black),
      borderRadius: BorderRadius.circular(18),
    ),
    focusedBorder: OutlineInputBorder(
      borderSide: BorderSide(color: Colors.green[900]!, width: 2),
      borderRadius: BorderRadius.circular(18),
    ),
    focusColor: Colors.black,
  );
}

extension ShowSnackBar on BuildContext {
  void showErrorMessage(String message) {
    ScaffoldMessenger.of(this).showSnackBar(
      SnackBar(
        content: Text(
          message,
          style: GoogleFonts.pressStart2p(),
        ),
      ),
    );
  }
}

class LowerCaseTextFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(
      TextEditingValue oldValue, TextEditingValue newValue) {
    return TextEditingValue(
      text: newValue.text.toLowerCase(),
      selection: newValue.selection,
    );
  }
}

final List<Map<String, dynamic>> countries = [
  {'name': 'Afghanistan', 'flag': 'AF'},
  {'name': 'Albania', 'flag': 'AL'},
  {'name': 'Algeria', 'flag': 'DZ'},
  {'name': 'American Samoa', 'flag': 'AS'},
  {'name': 'Andorra', 'flag': 'AD'},
  {'name': 'Angola', 'flag': 'AO'},
  {'name': 'Anguilla', 'flag': 'AI'},
  {'name': 'Antarctica', 'flag': 'AQ'},
  {'name': 'Antigua and Barbuda', 'flag': 'AG'},
  {'name': 'Argentina', 'flag': 'AR'},
  {'name': 'Aruba', 'flag': 'AW'},
  {'name': 'Australia', 'flag': 'AU'},
  {'name': 'Austria', 'flag': 'AT'},
  {'name': 'Azerbaijan', 'flag': 'AZ'},
  {'name': 'Bahamas (the)', 'flag': 'BS'},
  {'name': 'Bahrain', 'flag': 'BH'},
  {'name': 'Bangladesh', 'flag': 'BD'},
  {'name': 'Barbados', 'flag': 'BB'},
  {'name': 'Belarus', 'flag': 'BY'},
  {'name': 'Belgium', 'flag': 'BE'},
  {'name': 'Belize', 'flag': 'BZ'},
  {'name': 'Benin', 'flag': 'BJ'},
  {'name': 'Bermuda', 'flag': 'BM'},
  {'name': 'Bhutan', 'flag': 'BT'},
  {'name': 'Bolivia (Plurinational State of)', 'flag': 'BO'},
  {'name': 'Bonaire, Sint Eustatius and Saba', 'flag': 'BQ'},
  {'name': 'Bosnia and Herzegovina', 'flag': 'BA'},
  {'name': 'Botswana', 'flag': 'BW'},
  {'name': 'Bouvet Island', 'flag': 'BV'},
  {'name': 'Brazil', 'flag': 'BR'},
  {'name': 'British Indian Ocean Territory (the)', 'flag': 'IO'},
  {'name': 'Brunei Darussalam', 'flag': 'BN'},
  {'name': 'Bulgaria', 'flag': 'BG'},
  {'name': 'Burkina Faso', 'flag': 'BF'},
  {'name': 'Burundi', 'flag': 'BI'},
  {'name': 'Cabo Verde', 'flag': 'CV'},
  {'name': 'Cambodia', 'flag': 'KH'},
  {'name': 'Cameroon', 'flag': 'CM'},
  {'name': 'Canada', 'flag': 'CA'},
  {'name': 'Cayman Islands (the)', 'flag': 'KY'},
  {'name': 'Central African Republic (the)', 'flag': 'CF'},
  {'name': 'Chad', 'flag': 'TD'},
  {'name': 'Chile', 'flag': 'CL'},
  {'name': 'China', 'flag': 'CN'},
  {'name': 'Christmas Island', 'flag': 'CX'},
  {'name': 'Cocos (Keeling) Islands (the)', 'flag': 'CC'},
  {'name': 'Colombia', 'flag': 'CO'},
  {'name': 'Comoros (the)', 'flag': 'KM'},
  {'name': 'Congo (the Democratic Republic of the)', 'flag': 'CD'},
  {'name': 'Congo (the)', 'flag': 'CG'},
  {'name': 'Cook Islands (the)', 'flag': 'CK'},
  {'name': 'Costa Rica', 'flag': 'CR'},
  {'name': 'Croatia', 'flag': 'HR'},
  {'name': 'Cuba', 'flag': 'CU'},
  {'name': 'Curaçao', 'flag': 'CW'},
  {'name': 'Cyprus', 'flag': 'CY'},
  {'name': 'Czechia', 'flag': 'CZ'},
  {'name': "Côte d'Ivoire", 'flag': 'CI'},
  {'name': 'Denmark', 'flag': 'DK'},
  {'name': 'Djibouti', 'flag': 'DJ'},
  {'name': 'Dominica', 'flag': 'DM'},
  {'name': 'Dominican Republic (the)', 'flag': 'DO'},
  {'name': 'Ecuador', 'flag': 'EC'},
  {'name': 'Egypt', 'flag': 'EG'},
  {'name': 'El Salvador', 'flag': 'SV'},
  {'name': 'Equatorial Guinea', 'flag': 'GQ'},
  {'name': 'Eritrea', 'flag': 'ER'},
  {'name': 'Estonia', 'flag': 'EE'},
  {'name': 'Eswatini', 'flag': 'SZ'},
  {'name': 'Ethiopia', 'flag': 'ET'},
  {'name': 'Falkland Islands (the)', 'flag': 'FK'},
  {'name': 'Faroe Islands (the)', 'flag': 'FO'},
  {'name': 'Fiji', 'flag': 'FJ'},
  {'name': 'Finland', 'flag': 'FI'},
  {'name': 'France', 'flag': 'FR'},
  {'name': 'French Guiana', 'flag': 'GF'},
  {'name': 'French Polynesia', 'flag': 'PF'},
  {'name': 'French Southern Territories (the)', 'flag': 'TF'},
  {'name': 'Gabon', 'flag': 'GA'},
  {'name': 'Gambia (the)', 'flag': 'GM'},
  {'name': 'Georgia', 'flag': 'GE'},
  {'name': 'Germany', 'flag': 'DE'},
  {'name': 'Ghana', 'flag': 'GH'},
  {'name': 'Gibraltar', 'flag': 'GI'},
  {'name': 'Greece', 'flag': 'GR'},
  {'name': 'Greenland', 'flag': 'GL'},
  {'name': 'Grenada', 'flag': 'GD'},
  {'name': 'Guadeloupe', 'flag': 'GP'},
  {'name': 'Guam', 'flag': 'GU'},
  {'name': 'Guatemala', 'flag': 'GT'},
  {'name': 'Guernsey', 'flag': 'GG'},
  {'name': 'Guinea', 'flag': 'GN'},
  {'name': 'Guinea-Bissau', 'flag': 'GW'},
  {'name': 'Guyana', 'flag': 'GY'},
  {'name': 'Haiti', 'flag': 'HT'},
  {'name': 'Heard Island and McDonald Islands', 'flag': 'HM'},
  {'name': 'Holy See (the)', 'flag': 'VA'},
  {'name': 'Honduras', 'flag': 'HN'},
  {'name': 'Hong Kong', 'flag': 'HK'},
  {'name': 'Hungary', 'flag': 'HU'},
  {'name': 'Iceland', 'flag': 'IS'},
  {'name': 'India', 'flag': 'IN'},
  {'name': 'Indonesia', 'flag': 'ID'},
  {'name': 'Iran (Islamic Republic of)', 'flag': 'IR'},
  {'name': 'Iraq', 'flag': 'IQ'},
  {'name': 'Ireland', 'flag': 'IE'},
  {'name': 'Isle of Man', 'flag': 'IM'},
  {'name': 'Israel', 'flag': 'IL'},
  {'name': 'Italy', 'flag': 'IT'},
  {'name': 'Jamaica', 'flag': 'JM'},
  {'name': 'Japan', 'flag': 'JP'},
  {'name': 'Jersey', 'flag': 'JE'},
  {'name': 'Jordan', 'flag': 'JO'},
  {'name': 'Kazakhstan', 'flag': 'KZ'},
  {'name': 'Kenya', 'flag': 'KE'},
  {'name': 'Kiribati', 'flag': 'KI'},
  {'name': "Korea (the Democratic People's Republic of)", 'flag': 'KP'},
  {'name': 'Korea (the Republic of)', 'flag': 'KR'},
  {'name': 'Kuwait', 'flag': 'KW'},
  {'name': 'Kyrgyzstan', 'flag': 'KG'},
  {'name': "Lao People's Democratic Republic (the)", 'flag': 'LA'},
  {'name': 'Latvia', 'flag': 'LV'},
  {'name': 'Lebanon', 'flag': 'LB'},
  {'name': 'Lesotho', 'flag': 'LS'},
  {'name': 'Liberia', 'flag': 'LR'},
  {'name': 'Libya', 'flag': 'LY'},
  {'name': 'Liechtenstein', 'flag': 'LI'},
  {'name': 'Lithuania', 'flag': 'LT'},
  {'name': 'Luxembourg', 'flag': 'LU'},
  {'name': 'Macao', 'flag': 'MO'},
  {'name': 'Madagascar', 'flag': 'MG'},
  {'name': 'Malawi', 'flag': 'MW'},
  {'name': 'Malaysia', 'flag': 'MY'},
  {'name': 'Maldives', 'flag': 'MV'},
  {'name': 'Mali', 'flag': 'ML'},
  {'name': 'Malta', 'flag': 'MT'},
  {'name': 'Marshall Islands (the)', 'flag': 'MH'},
  {'name': 'Martinique', 'flag': 'MQ'},
  {'name': 'Mauritania', 'flag': 'MR'},
  {'name': 'Mauritius', 'flag': 'MU'},
  {'name': 'Mayotte', 'flag': 'YT'},
  {'name': 'Mexico', 'flag': 'MX'},
  {'name': 'Micronesia (Federated States of)', 'flag': 'FM'},
  {'name': 'Moldova (the Republic of)', 'flag': 'MD'},
  {'name': 'Monaco', 'flag': 'MC'},
  {'name': 'Mongolia', 'flag': 'MN'},
  {'name': 'Montenegro', 'flag': 'ME'},
  {'name': 'Montserrat', 'flag': 'MS'},
  {'name': 'Morocco', 'flag': 'MA'},
  {'name': 'Mozambique', 'flag': 'MZ'},
  {'name': 'Myanmar', 'flag': 'MM'},
  {'name': 'Namibia', 'flag': 'NA'},
  {'name': 'Nauru', 'flag': 'NR'},
  {'name': 'Nepal', 'flag': 'NP'},
  {'name': 'Netherlands (the)', 'flag': 'NL'},
  {'name': 'New Caledonia', 'flag': 'NC'},
  {'name': 'New Zealand', 'flag': 'NZ'},
  {'name': 'Nicaragua', 'flag': 'NI'},
  {'name': 'Niger (the)', 'flag': 'NE'},
  {'name': 'Nigeria', 'flag': 'NG'},
  {'name': 'Niue', 'flag': 'NU'},
  {'name': 'Norfolk Island', 'flag': 'NF'},
  {'name': 'Northern Mariana Islands (the)', 'flag': 'MP'},
  {'name': 'Norway', 'flag': 'NO'},
  {'name': 'Oman', 'flag': "OM"},
  //rest
  {'name': 'Pakistan', 'flag': 'PK'},
  {'name': 'Palau', 'flag': 'PW'},
  {'name': 'Palestine, State of', 'flag': 'PS'},
  {'name': 'Panama', 'flag': 'PA'},
  {'name': 'Papua New Guinea', 'flag': 'PG'},
  {'name': 'Paraguay', 'flag': 'PY'},
  {'name': 'Peru', 'flag': 'PE'},
  {'name': 'Philippines', 'flag': 'PH'},
  {'name': 'Pitcairn', 'flag': 'PN'},
  {'name': 'Poland', 'flag': 'PL'},
  {'name': 'Portugal', 'flag': 'PT'},
  {'name': 'Puerto Rico', 'flag': 'PR'},
  {'name': 'Qatar', 'flag': 'QA'},
  {'name': 'Republic of North Macedonia', 'flag': 'MK'},
  {'name': 'Romania', 'flag': 'RO'},
  {'name': 'Russian Federation', 'flag': 'RU'},
  {'name': 'Rwanda', 'flag': 'RW'},
  {'name': 'Réunion', 'flag': 'RE'},
  {'name': 'Saint Barthélemy', 'flag': 'BL'},
  {'name': 'Saint Helena, Ascension and Tristan da Cunha', 'flag': 'SH'},
  {'name': 'Saint Kitts and Nevis', 'flag': 'KN'},
  {'name': 'Saint Lucia', 'flag': 'LC'},
  {'name': 'Saint Martin (French part)', 'flag': 'MF'},
  {'name': 'Saint Pierre and Miquelon', 'flag': 'PM'},
  {'name': 'Saint Vincent and the Grenadines', 'flag': 'VC'},
  {'name': 'Samoa', 'flag': 'WS'},
  {'name': 'San Marino', 'flag': 'SM'},
  {'name': 'Sao Tome and Principe', 'flag': 'ST'},
  {'name': 'Saudi Arabia', 'flag': 'SA'},
  {'name': 'Senegal', 'flag': 'SN'},
  {'name': 'Serbia', 'flag': 'RS'},
  {'name': 'Seychelles', 'flag': 'SC'},
  {'name': 'Sierra Leone', 'flag': 'SL'},
  {'name': 'Singapore', 'flag': 'SG'},
  {'name': 'Sint Maarten (Dutch part)', 'flag': 'SX'},
  {'name': 'Slovakia', 'flag': 'SK'},
  {'name': 'Slovenia', 'flag': 'SI'},
  {'name': 'Solomon Islands', 'flag': 'SB'},
  {'name': 'Somalia', 'flag': 'SO'},
  {'name': 'South Africa', 'flag': 'ZA'},
  {'name': 'South Georgia and the South Sandwich Islands', 'flag': 'GS'},
  {'name': 'South Sudan', 'flag': 'SS'},
  {'name': 'Spain', 'flag': 'ES'},
  {'name': 'Sri Lanka', 'flag': 'LK'},
  {'name': 'Sudan', 'flag': 'SD'},
  {'name': 'Suriname', 'flag': 'SR'},
  {'name': 'Svalbard and Jan Mayen', 'flag': 'SJ'},
  {'name': 'Sweden', 'flag': 'SE'},
  {'name': 'Switzerland', 'flag': 'CH'},
  {'name': 'Syrian Arab Republic', 'flag': 'SY'},
  {'name': 'Taiwan (Province of China)', 'flag': 'TW'},
  {'name': 'Tajikistan', 'flag': 'TJ'},
  {'name': 'Tanzania, United Republic of', 'flag': 'TZ'},
  {'name': 'Thailand', 'flag': 'TH'},
  {'name': 'Timor-Leste', 'flag': 'TL'},
  {'name': 'Togo', 'flag': 'TG'},
  {'name': 'Tokelau', 'flag': 'TK'},
  {'name': 'Tonga', 'flag': 'TO'},
  {'name': 'Trinidad and Tobago', 'flag': 'TT'},
  {'name': 'Tunisia', 'flag': 'TN'},
  {'name': 'Turkey', 'flag': 'TR'},
  {'name': 'Turkmenistan', 'flag': 'TM'},
  {'name': 'Turks and Caicos Islands', 'flag': 'TC'},
  {'name': 'Tuvalu', 'flag': 'TV'},
  {'name': 'Uganda', 'flag': 'UG'},
  {'name': 'Ukraine', 'flag': 'UA'},
  {'name': 'United Arab Emirates', 'flag': 'AE'},
  {
    'name': 'United Kingdom of Great Britain and Northern Ireland',
    'flag': 'GB'
  },
  {'name': 'United States Minor Outlying Islands', 'flag': 'UM'},
  {'name': 'United States of America', 'flag': 'US'},
  {'name': 'Uruguay', 'flag': 'UY'},
  {'name': 'Uzbekistan', 'flag': 'UZ'},
  {'name': 'Vanuatu', 'flag': 'VU'},
  {'name': 'Venezuela (Bolivarian Republic of)', 'flag': 'VE'},
  {'name': 'Viet Nam', 'flag': 'VN'},
  {'name': 'Virgin Islands (British)', 'flag': 'VG'},
  {'name': 'Virgin Islands (U.S.)', 'flag': 'VI'},
  {'name': 'Wallis and Futuna', 'flag': 'WF'},
  {'name': 'Western Sahara', 'flag': 'EH'},
  {'name': 'Yemen', 'flag': 'YE'},
  {'name': 'Zambia', 'flag': 'ZM'},
  {'name': 'Zimbabwe', 'flag': 'ZW'},
  {'name': 'Åland Islands', 'flag': 'AX'},
];

String getFlagForCountry(String countryName) {
  final country = countries.firstWhere(
    (element) => element['name'] == countryName,
    orElse: () =>
        {'flag': 'Not found'}, // Default value if country is not found
  );
  return country['flag'];
}
